
// Model Under Test (MUT) Metadata.
// This file is automatically generated by neuralspot's tflm_validate tool
#ifndef __MUT_MODEL_METADATA_H
#define __MUT_MODEL_METADATA_H

// Calculated Arena and RPC buffer sizes
#define TFLM_VALIDATOR_ARENA_SIZE 99
#define TFLM_VALIDATOR_RX_BUFSIZE 4096
#define TFLM_VALIDATOR_TX_BUFSIZE 4096
#endif // __MUT_MODEL_METADATA_H
