#ifndef __MUT_MODEL_METADATA_H
#define __MUT_MODEL_METADATA_H

// Default Arena and RPC buffer sizes
#define TFLM_VALIDATOR_ARENA_SIZE 75
#define TFLM_VALIDATOR_RX_BUFSIZE 4096
#define TFLM_VALIDATOR_TX_BUFSIZE 4096

#define TFLM_VALIDATOR_MAX_RESOURCE_VARIABLES 15

#endif
