include make/helpers.mk
include make/neuralspot_config.mk
include make/neuralspot_toolchain.mk
#include make/jlink.mk

# Collect information from each module in these four variables.
# Initialize them here as simple variables.
modules      := extern/AmbiqSuite/$(AS_VERSION)
modules      += extern/tensorflow/$(TF_VERSION)

modules      += neuralspot/ns-harness 
modules      += neuralspot/ns-peripherals 
modules      += neuralspot/ns-ipc
modules      += neuralspot/ns-audio

modules      += examples/hello_world
modules      += examples/s2i
modules      += examples/basic_tf_stub

NESTSOURCE    := examples/basic_tf_stub/build/main.d
NESTSOURCEDIR := examples/basic_tf_stub/src

# These are filled in by subdir include files, pulled in below
examples     :=
mains        :=
libraries    :=
lib_prebuilt :=
sources      :=
includes_api :=
pp_defines   := $(DEFINES)
bindirs      := $(BINDIR)

objects      = $(filter-out $(mains),$(call source-to-object,$(sources)))
dependencies = $(subst .o,.d,$(objects))

CFLAGS     += $(addprefix -D,$(pp_defines))
CFLAGS     += $(addprefix -I ,$(includes_api))

.PHONY: all
all:

include $(addsuffix /module.mk,$(modules))

all: $(bindirs) $(libraries) $(examples)

.PHONY: libraries
libraries: $(libraries)

.PHONY: clean
clean:
ifeq ($(OS),Windows_NT)
	@echo "Windows_NT"
	@echo $(Q) $(RM) -rf $(CONFIG)/*
	$(Q) $(RM) -rf $(bindirs)/*
else
	$(Q) $(RM) -rf $(bindirs) $(JLINK_CF)
endif

ifneq "$(MAKECMDGOALS)" "clean"
  include $(dependencies)
endif

all_includes = $(shell awk '/^ .*\.h/ {print $$1}' $(NESTSOURCE))
nest_dirs = $(sort $(dir $(all_includes)))
nest_libs = $(addprefix libs/,$(notdir $(libraries)))
nest_libs += $(addprefix libs/,$(notdir $(lib_prebuilt)))
doc_sources = $(addprefix ../../,$(sources))
doc_sources += $(addprefix ../../,$(includes_api))

$(bindirs):
	@mkdir -p $@

%.o: ../src/%.cc
	@echo " Compiling $(COMPILERNAME) $< to make $@"
	@mkdir -p $(@D)
	$(Q) $(CC) -c $(CFLAGS) $(CCFLAGS) $< -o $@

%.o: ../src/%.c
	@echo " Compiling $(COMPILERNAME) $< to make $@"
	@mkdir -p $(@D)
	$(Q) $(CC) -c $(CFLAGS) $(CONLY_FLAGS) $< -o $@

%.o: ../src/%.s
	@echo " Assembling $(COMPILERNAME) $<"
	@mkdir -p $(@D)
	$(Q) $(CC) -c $(CFLAGS) $< -o $@

%.axf: %.o $(objects) $(libraries)
	@echo " Linking $(COMPILERNAME) $@"
	@mkdir -p $(@D)
	$(Q) $(CC) -Wl,-T,$(LINKER_FILE) -o $@ $< $(objects) $(LFLAGS)

%.bin: %.axf 
	@echo " Copying $(COMPILERNAME) $@..."
	@mkdir -p $(@D)
	$(Q) $(CP) $(CPFLAGS) $< $@
	$(Q) $(OD) $(ODFLAGS) $< > $*.lst
	$(Q) $(SIZE) $(objects) $(lib_prebuilt) $< > $*.size

.PHONY: docs
docs:
	@echo " Making Documents"
	@echo "INCLUDES = $(doc_sources)"
	@echo "EXCLUDE_PATTERNS = */AmbiqSuite/* */tensorflow/* */$(BINDIR)/* */$(NESTDIR)/*"
#	@echo "H_INCLUDES = $(all_includes)"
#	$(Q) $(DOX) docs/Doxyfile

.PHONY: nest
nest: all $(NESTSOURCE)
	@echo " Building Nest at $(NESTDIR) based on $< ..."
	@mkdir -p $(NESTDIR)
	@mkdir -p $(NESTDIR)/src	
	@mkdir -p $(NESTDIR)/libs	
	@for target in $(nest_dirs); do \
		mkdir -p $(NESTDIR)"/includes/"$$target ; \
	done
	@for file in $(all_includes); do \
		cp $$file $(NESTDIR)"/includes/"$$file ; \
	done
	@for file in $(libraries); do \
		cp $$file $(NESTDIR)"/libs/" ; \
	done	
	@for file in $(lib_prebuilt); do \
		cp $$file $(NESTDIR)"/libs/" ; \
	done
	@cp $(NESTSOURCEDIR)/* $(NESTDIR)/src
	@cp $(LINKER_FILE) $(NESTDIR)/libs
	@cp make/nest-makefile.mk $(NESTDIR)/Makefile
	@echo "# Autogenerated file - created by NeuralSPOT make nest" > $(NESTDIR)/autogen.mk
	@echo "DEFINES += $(pp_defines)" >> $(NESTDIR)/autogen.mk
	@echo "INCLUDES += $(includes_api)" >> $(NESTDIR)/autogen.mk
	@echo "libraries += $(nest_libs)" >> $(NESTDIR)/autogen.mk

%.d: ;
