[project]
name = "neuralspot"
version = "0.0.1"
description =  "Autodeploy is an all-in-one tool for automatically deploy, testing, profiling, and package TFLite files on Ambiq EVBs."
readme = "README.md"
authors = [
    {name="Ambiq AI", email="support.aitg@ambiq.com"}
]
requires-python = ">= 3.10"
dependencies = [
    "numpy>=1.21.6",
    "soundfile>=0.10.3",
    "pyserial~=3.5",
    "pydantic-argparse~=0.9.0",
    "pydantic~=1.8.2",
    "joulescope>=1.1.15",
    "tensorflow~=2.17.0",
    "tabulate>=0.9.0",
    "tqdm>=4.66.5",
    "PyOgg",
    "Wave~=0.0.2",
    "erpc@git+https://github.com/ambiqai/erpc.git#egg=devewhlop&subdirectory=erpc_python",
    "PyYAML>=6.0.2"
]

<<<<<<< HEAD
[tool.setuptools]
packages=[
    "neuralspot",
    "neuralspot.rpc",
    "neuralspot.rpc.GenericDataOperations_EvbToPc",
    "neuralspot.rpc.GenericDataOperations_PcToEvb",
    "neuralspot.tools",
]
=======
[project.urls]
Homepage = "https://github.com/ambiqai/neuralSPOT"
Documentation = "https://ambiqai.github.io/neuralSPOT"
Repository = "https://github.com/ambiqai/neuralSPOT"
>>>>>>> origin/main


[tool.setuptools]
packages=[
    "neuralspot",
    "neuralspot.rpc",
    "neuralspot.rpc.GenericDataOperations_EvbToPc",
    "neuralspot.rpc.GenericDataOperations_PcToEvb",
]

[tool.setuptools.package-dir]
neuralspot = ""
"neuralspot.rpc" = "neuralspot/ns-rpc/python/ns-rpc-genericdata"
"neuralspot.rpc.GenericDataOperations_EvbToPc" = "neuralspot/ns-rpc/python/ns-rpc-genericdata/GenericDataOperations_EvbToPc"
"neuralspot.rpc.GenericDataOperations_PcToEvb" = "neuralspot/ns-rpc/python/ns-rpc-genericdata/GenericDataOperations_PcToEvb"
"neuralspot.tools" = "tools"

[tool.setuptools.package-data]
neuralspot = ["tools/autodeploy/templates/**/*"]

[project.scripts]
ns_autodeploy = "neuralspot.tools.ns_autodeploy:main"
ns_perf = "neuralspot.tools.ns_perf:main"

[project.urls]
Homepage = "https://github.com/ambiqai/neuralSPOT"
Documentation = "https://ambiqai.github.io/neuralSPOT"
Repository = "https://github.com/ambiqai/neuralSPOT"




[build-system]
requires = ["setuptools >= 61.0", "wheel"]
build-backend = "setuptools.build_meta"