#include "ns_ambiqsuite_harness.h"
void ns_harness_tests_pre_test_hook();
void ns_harness_tests_post_test_hook();
void itm_enable_noCoreInitTest();
void ns_itm_printf_enable_test();
void ns_itm_printf_disable_test();
void ns_lp_printf_no_itm_uart_test();
void itm_uart_enabled_test();
void poorly_formatted_string_test();
void uart_enabled_test();
