#ifndef __MUT_MODEL_METADATA_H
#define __MUT_MODEL_METADATA_H

// Default Arena and RPC buffer sizes
#define TFLM_VALIDATOR_ARENA_SIZE 120
#define TFLM_VALIDATOR_RX_BUFSIZE 2048
#define TFLM_VALIDATOR_TX_BUFSIZE 2048

#endif
