#pragma once
#ifndef __MUT_MODEL_METADATA_H
#define __MUT_MODEL_METADATA_H
#include "ns_ambiqsuite_harness.h"

// Default Arena and RPC buffer sizes
#define TFLM_VALIDATOR_ARENA_SIZE 323
#define TFLM_VALIDATOR_RX_BUFSIZE 4096
#define TFLM_VALIDATOR_TX_BUFSIZE 4096
#define TFLM_VALIDATOR_MAX_RESOURCE_VARIABLES_F2M 0

#define TFLM_MODEL_LOCATION_F2M NS_AD_MRAM
#define TFLM_ARENA_LOCATION_F2M NS_AD_SRAM
#define NS_AD_AOT           0   /* 0 = TFLM, 1 = AOT */
#define AOT_NUM_LAYERS      0
#define AOT_LAST_IDENTIFIER 0

#define TFLM_VALIDATOR_MAC_ESTIMATE_COUNT 127

#ifdef AM_PART_APOLLO5B
#define NS_PROFILER_PMU_EVENT_0 ARM_PMU_MVE_INST_RETIRED
#define NS_PROFILER_PMU_EVENT_1 ARM_PMU_MVE_INT_MAC_RETIRED
#define NS_PROFILER_PMU_EVENT_2 ARM_PMU_INST_RETIRED
#define NS_PROFILER_PMU_EVENT_3 ARM_PMU_BUS_CYCLES
#endif

#define NS_VALIDATOR_RPC_TRANSPORT NS_AD_RPC_TRANSPORT_USB

#endif