
// TFLite Per-Layer Estimated MAC counts, generated by ns_tflite_profile.py

uint32_t kws_ref_model_mac_estimates[] = {
    5000, 72000, 8000, 72000, 8000, 72000, 8000, 72000, 8000, 0, 0, 768, 0,
};

const int kws_ref_model_number_of_estimates = 13;
