#include "ns_peripherals_button.h"
void ns_button_tests_pre_test_hook();
void ns_button_tests_post_test_hook();
void ns_button_basic_init_test();
void ns_button_init_null_test();
void ns_button_invalid_api_test();
void ns_button_init_both_buttons_enable_test();
void ns_button_init_both_buttons_disable_test();
void ns_button_init_joulescope_trigger_enable_test();
void ns_button_enable_no_flag_test();
void ns_button_joulescope_enable_no_flag_test();