#@file ns-audio-rpc.erpc
#
# @brief Interface definition for neuralspot audio RPC
#
#

#
# Generated by erpcgen 1.9.1 on Thu Aug 25 16:33:20 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for ns_audio_rpc
class ns_audio_rpcClient(interface.Ins_audio_rpc):
    def __init__(self, manager):
        super(ns_audio_rpcClient, self).__init__()
        self._clientManager = manager

    def erpcDumpAudioBuffer(self, buf):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        codec = request.codec
        codec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.ERPCDUMPAUDIOBUFFER_ID,
                sequence=request.sequence))
        if buf is None:
            raise ValueError("buf is None")
        buf._write(codec)

        # Send request and process reply.
        self._clientManager.perform_request(request)
        _result = codec.read_uint32()
        return _result


