#@file ns-audio-rpc.erpc
#
# @brief Interface definition for neuralspot audio RPC
#
#

#
# Generated by erpcgen 1.9.1 on Thu Aug 25 16:33:20 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for ns_audio_rpc
class Ins_audio_rpc(object):
    SERVICE_ID = 1
    ERPCDUMPAUDIOBUFFER_ID = 1

    def erpcDumpAudioBuffer(self, buf):
        raise NotImplementedError()


