#@file ns-audio-rpc.erpc
#
# @brief Interface definition for neuralspot audio RPC
#
#

#
# Generated by erpcgen 1.9.1 on Thu Aug 25 16:33:20 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for ns_audio_rpc
class ns_audio_rpcService(erpc.server.Service):
    def __init__(self, handler):
        super(ns_audio_rpcService, self).__init__(interface.Ins_audio_rpc.SERVICE_ID)
        self._handler = handler
        self._methods = {
                interface.Ins_audio_rpc.ERPCDUMPAUDIOBUFFER_ID: self._handle_erpcDumpAudioBuffer,
            }

    def _handle_erpcDumpAudioBuffer(self, sequence, codec):
        # Read incoming parameters.
        buf = common.audioCommand_t()._read(codec)

        # Invoke user implementation of remote function.
        _result = self._handler.erpcDumpAudioBuffer(buf)

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.Ins_audio_rpc.SERVICE_ID,
            request=interface.Ins_audio_rpc.ERPCDUMPAUDIOBUFFER_ID,
            sequence=sequence))
        codec.write_uint32(_result)


