// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_USBPACKET_WEB_USB_H_
#define FLATBUFFERS_GENERATED_USBPACKET_WEB_USB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace web {
namespace usb {

struct UsbPacket;
struct UsbPacketBuilder;

enum UsbDataType : int8_t {
  UsbDataType_NONE = 0,
  UsbDataType_SET_SE_MODE = 1,
  UsbDataType_SE_LATENCY = 2,
  UsbDataType_OPUS_LATENCY = 3,
  UsbDataType_AUDIO_DATA = 4,
  UsbDataType_MIN = UsbDataType_NONE,
  UsbDataType_MAX = UsbDataType_AUDIO_DATA
};

inline const UsbDataType (&EnumValuesUsbDataType())[5] {
  static const UsbDataType values[] = {
    UsbDataType_NONE,
    UsbDataType_SET_SE_MODE,
    UsbDataType_SE_LATENCY,
    UsbDataType_OPUS_LATENCY,
    UsbDataType_AUDIO_DATA
  };
  return values;
}

inline const char * const *EnumNamesUsbDataType() {
  static const char * const names[6] = {
    "NONE",
    "SET_SE_MODE",
    "SE_LATENCY",
    "OPUS_LATENCY",
    "AUDIO_DATA",
    nullptr
  };
  return names;
}

inline const char *EnumNameUsbDataType(UsbDataType e) {
  if (::flatbuffers::IsOutRange(e, UsbDataType_NONE, UsbDataType_AUDIO_DATA)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesUsbDataType()[index];
}

enum Platform : int8_t {
  Platform_APOLLO3 = 0,
  Platform_APOLLO4 = 1,
  Platform_APOLLO5 = 2,
  Platform_MIN = Platform_APOLLO3,
  Platform_MAX = Platform_APOLLO5
};

inline const Platform (&EnumValuesPlatform())[3] {
  static const Platform values[] = {
    Platform_APOLLO3,
    Platform_APOLLO4,
    Platform_APOLLO5
  };
  return values;
}

inline const char * const *EnumNamesPlatform() {
  static const char * const names[4] = {
    "APOLLO3",
    "APOLLO4",
    "APOLLO5",
    nullptr
  };
  return names;
}

inline const char *EnumNamePlatform(Platform e) {
  if (::flatbuffers::IsOutRange(e, Platform_APOLLO3, Platform_APOLLO5)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPlatform()[index];
}

struct UsbPacket FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UsbPacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_PLATFORM = 6,
    VT_SEQUENCE = 8,
    VT_VERSION = 10,
    VT_DATA = 12
  };
  web::usb::UsbDataType type() const {
    return static_cast<web::usb::UsbDataType>(GetField<int8_t>(VT_TYPE, 0));
  }
  web::usb::Platform platform() const {
    return static_cast<web::usb::Platform>(GetField<int8_t>(VT_PLATFORM, 0));
  }
  uint16_t sequence() const {
    return GetField<uint16_t>(VT_SEQUENCE, 0);
  }
  int8_t version() const {
    return GetField<int8_t>(VT_VERSION, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<int8_t>(verifier, VT_PLATFORM, 1) &&
           VerifyField<uint16_t>(verifier, VT_SEQUENCE, 2) &&
           VerifyField<int8_t>(verifier, VT_VERSION, 1) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
};

struct UsbPacketBuilder {
  typedef UsbPacket Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(web::usb::UsbDataType type) {
    fbb_.AddElement<int8_t>(UsbPacket::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_platform(web::usb::Platform platform) {
    fbb_.AddElement<int8_t>(UsbPacket::VT_PLATFORM, static_cast<int8_t>(platform), 0);
  }
  void add_sequence(uint16_t sequence) {
    fbb_.AddElement<uint16_t>(UsbPacket::VT_SEQUENCE, sequence, 0);
  }
  void add_version(int8_t version) {
    fbb_.AddElement<int8_t>(UsbPacket::VT_VERSION, version, 0);
  }
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(UsbPacket::VT_DATA, data);
  }
  explicit UsbPacketBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UsbPacket> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UsbPacket>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UsbPacket> CreateUsbPacket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    web::usb::UsbDataType type = web::usb::UsbDataType_NONE,
    web::usb::Platform platform = web::usb::Platform_APOLLO3,
    uint16_t sequence = 0,
    int8_t version = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0) {
  UsbPacketBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_sequence(sequence);
  builder_.add_version(version);
  builder_.add_platform(platform);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<UsbPacket> CreateUsbPacketDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    web::usb::UsbDataType type = web::usb::UsbDataType_NONE,
    web::usb::Platform platform = web::usb::Platform_APOLLO3,
    uint16_t sequence = 0,
    int8_t version = 0,
    const std::vector<uint8_t> *data = nullptr) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return web::usb::CreateUsbPacket(
      _fbb,
      type,
      platform,
      sequence,
      version,
      data__);
}

}  // namespace usb
}  // namespace web

#endif  // FLATBUFFERS_GENERATED_USBPACKET_WEB_USB_H_
