#pragma once
#ifndef __MUT_MODEL_METADATA_H
#define __MUT_MODEL_METADATA_H
#include "ns_ambiqsuite_harness.h"

// Default Arena and RPC buffer sizes
#define TFLM_VALIDATOR_ARENA_SIZE NS_AD_ARENA_SIZE
#define TFLM_VALIDATOR_RX_BUFSIZE NS_AD_RPC_BUFSIZE
#define TFLM_VALIDATOR_TX_BUFSIZE NS_AD_RPC_BUFSIZE
#define TFLM_VALIDATOR_MAX_RESOURCE_VARIABLES NS_AD_RV_COUNT

#define TFLM_MODEL_LOCATION NS_AD_MODEL_LOCATION
#define TFLM_ARENA_LOCATION NS_AD_ARENA_LOCATION
#define NS_AD_AOT           NS_AD_AOT_VALUE   /* 0 = TFLM, 1 = AOT */
#define AOT_NUM_LAYERS      NS_AD_AOT_NUM_LAYERS
#define AOT_LAST_IDENTIFIER NS_AD_AOT_LAST_IDENTIFIER

#define TFLM_VALIDATOR_MAC_ESTIMATE_COUNT NS_AD_MAC_ESTIMATE_COUNT

#if defined(AM_PART_APOLLO5B) || defined(AM_PART_APOLLO330P_510L) || defined(AM_PART_APOLLO330P)
#define NS_PROFILER_PMU_EVENT_0 NS_AD_PMU_EVENT_0
#define NS_PROFILER_PMU_EVENT_1 NS_AD_PMU_EVENT_1
#define NS_PROFILER_PMU_EVENT_2 NS_AD_PMU_EVENT_2
#define NS_PROFILER_PMU_EVENT_3 NS_AD_PMU_EVENT_3
#endif

#define NS_VALIDATOR_RPC_TRANSPORT NS_AD_TRANSPORT

#endif