// auto-generated by generate_nn_c_files
// arm_core = cortex-M55
#include <stdint.h>
#include "neural_nets.h"
#include "activation.h"
#include "affine.h"
#include "lstm.h"
#include "nn_speech.h"
#include "def_nn1_nnvad.h"

extern const int16_t stft_win_coeff[];

extern const int16_t filter_banks[];

PARAMS_NNSP params_nn1_nnvad = {
    .samplingRate = 16000,
    .fftsize = 512,
    .winsize_stft = 160,
    .hopsize_stft = 160,
    .num_mfltrBank = 0,
    .num_dnsmpl = 1,
    .pt_stft_win_coeff = stft_win_coeff,
    .p_melBanks = filter_banks,
    .start_bin = 0,
    .is_dcrm = 0,
    .pre_gain_q1 = 1 << 1, // q1
};

/*************stats***********/
const int32_t feature_mean_vad2[] = {};

const int32_t feature_stdR_vad2[] = {};
