#define LOCAL_MODEL_NAME NS_AD_NAME
// Calculated Arena size
#define NS_AD_NAME_COMPUTED_ARENA_SIZE NS_AD_ARENA_SIZE

#define NS_AD_NAME_MODEL_LOCATION NS_AD_MODEL_LOCATION
#define NS_AD_NAME_ARENA_LOCATION NS_AD_ARENA_LOCATION


