# automatically generated by the FlatBuffers compiler, do not modify

# namespace: usb

class UsbDataType(object):
    NONE = 0
    SET_SE_MODE = 1
    SE_LATENCY = 2
    OPUS_LATENCY = 3
    AUDIO_DATA = 4
    MODEL_DATA = 5
