MemorySections:
    MCU_MRAM:
        start:  0x00018000
        end:    0x001FFFFF

    MCU_TCM:
        # Coremark requires greater than 8KB TCM, next graduation is 128KB.
        start:  0x10000000
        length: 0x0001F000

    SHARED_SRAM:
        # With all shared RAM disabled, must allocate a small amount of TCM for it.
        start:  0x1001F000
        length: 0x00001000

    EXTENDED_SRAM:
        start:  0x10160000
        end:    0x101BFFFF

    SHARED_SRAM2:
        start:  0x101C0000
        end:    0x102BFFFF
