#GenericDataOperations PC-to-EVB Definition
#/
#/ USe this as the client on the PC and server on EVB

#
# Generated by erpcgen 1.9.1 on Thu Sep  8 16:37:57 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for pc_to_evb
class Ipc_to_evb(object):
    SERVICE_ID = 1
    NS_RPC_DATA_SENDBLOCKTOEVB_ID = 1
    NS_RPC_DATA_FETCHBLOCKFROMEVM_ID = 2
    NS_RPC_DATA_COMPUTEONEVB_ID = 3

    def ns_rpc_data_sendBlockToEVB(self, block):
        raise NotImplementedError()

    def ns_rpc_data_fetchBlockFromEVM(self, block):
        raise NotImplementedError()

    def ns_rpc_data_computeOnEVB(self, in_block, result_block):
        raise NotImplementedError()


