#ifndef __MUT_MODEL_METADATA_H
#define __MUT_MODEL_METADATA_H

// Default Arena and RPC buffer sizes
#define TFLM_VALIDATOR_ARENA_SIZE NS_AD_ARENA_SIZE
#define TFLM_VALIDATOR_RX_BUFSIZE NS_AD_RPC_BUFSIZE
#define TFLM_VALIDATOR_TX_BUFSIZE NS_AD_RPC_BUFSIZE

#define TFLM_VALIDATOR_MAX_RESOURCE_VARIABLES NS_AD_RV_COUNT

#endif
