#include "ns_ble.h"
void ns_ble_tests_pre_test_hook();
void ns_ble_tests_post_test_hook();
void ns_ble_create_service_test();
void ns_ble_create_service_test_no_characteristics();
void ns_ble_create_null_service_test();
void ns_ble_negative_attribute_test();
void ns_ble_create_different_service_test();
void ns_ble_characteristic_test();
void ns_ble_multiple_characteristics_test();
void ns_ble_multiple_characteristics_fail_test();
void ns_ble_empty_service_add_characteristic_test();
void ns_ble_start_service_test();