# Put your local overrides in here
# BOARD :=apollo4l
# EVB    :=blue_kbr_evb
# EVB    :=blue_evb
# TARGET :=web_ble
# DEFINES+= CFG_TUSB_DEBUG=2
# TF_VERSION := R2.3.1
# TF_VERSION := 0264234_Nov_15_2023
# AS_VERSION := R4.3.0
# TOOLCHAIN := arm

# DEFINES+= NS_AUDIO_DMA_BUFFER_SIZE=16000
# DEFINES+= NS_MALLOC_HEAP_SIZE_IN_K=32
# STACK_SIZE_IN_32B_WORDS := 8192
# NS_MALLOC_HEAP_SIZE_IN_K := 32
# DEFINES += DEF_ACC32BIT_OPT
# DEFINES+= WSF_TRACE_ENABLED
# DEFINES+= HCI_TRACE_ENABLED
