# Put your local overrides in here
# PLATFORM := apollo4p_blue_kbr_evb
# TARGET :=web_ble

# TF_VERSION := 0264234_Nov_15_2023
# AS_VERSION := R4.3.0
# TOOLCHAIN := arm
# GCC13_EXPERIMENTAL := 1
# DEFINES+= NS_AUDIO_DMA_BUFFER_SIZE=16000
# DEFINES+= NS_MALLOC_HEAP_SIZE_IN_K=32
# LEGACY_MALLOC := 1
# STACK_SIZE_IN_32B_WORDS := 8192
# NS_MALLOC_HEAP_SIZE_IN_K := 32
# DEFINES += DEF_ACC32BIT_OPT
# DEFINES+= WSF_TRACE_ENABLED
# DEFINES+= HCI_TRACE_ENABLED
# DEFINES+= CFG_TUSB_DEBUG=2