/******************************************************************************
 * @file        str_ww_ref_model_fully_connected_9.c
 * @brief       Autogenerated AOT FULLY_CONNECTED kernel
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-08-05.
 *   This kernel represents node #9 in the corresponding graph.
 *
 * @date        2025-08-05
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/
#include <stdalign.h>
#include "ns_ambiqsuite_harness.h"
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "str_ww_ref_model_fully_connected_9.h"

// Input dimensions: input shape is [N, H, W, C_IN]
static const cmsis_nn_dims fc_9_input_dims = { .n = 1, .h = 1, .w = 1, .c = 32 };

// Filter dimensions: weights shape is [(H * W * C_IN), 1, 1, C_OUT].
static const cmsis_nn_dims fc_9_filter_dims = { .n = 32, .h = 1, .w = 1, .c = 3 };

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims fc_9_bias_dims = { .n = 1, .h = 1, .w = 1, .c = 3 };

// Output dimensions: output shape is [N, 1, 1, C_OUT].
static const cmsis_nn_dims fc_9_output_dims = { .n = 1, .h = 1, .w = 1, .c = 3 };

// Quantization parameters (per-channel quantization)
static const int32_t fc_9_multiplier[] = {
    1898836736
};
static const int32_t fc_9_shift[] = {
    -9
};

// Offsets and activation parameters.
static const int32_t fc_9_input_zero_point = -128;
static const int32_t fc_9_filter_zero_point = 0;
static const int32_t fc_9_output_zero_point = 10;

// Weight and bias data.
alignas(16) static NS_PUT_IN_TCM int8_t fc_9_weights[] = {
    -25, -26, -45, -43, -8, 34, -84, -10, -34, 21, -68, -29, -67, -55, -70, -67, -37, 59, -83, 43,
    44, 47, 48, -16, -65, 20, -53, 14, 48, 26, 33, -44, -24, -79, -25, 15, -57, -122, 7, -99,
    67, 27, 35, -65, -18, -27, 43, 50, 53, 33, 28, -43, -80, -109, -28, -44, 13, -127, 55, -36,
    -32, -63, -96, -32, 61, 61, 54, 55, 55, 53, -39, 48, 8, -62, -6, 33, 39, 31, 7, -35,
    30, -30, -19, 2, 54, 39, -21, 63, -10, 17, -25, -50, -33, 61, 12, 30
};

alignas(16) static NS_PUT_IN_TCM int32_t fc_9_bias[] = {
    210, -2624, 709
};


alignas(16) static NS_PUT_IN_TCM int32_t fc_9_kernel_sum[3];

static cmsis_nn_context fc_9_ctx = {
    .buf = (void *)fc_9_kernel_sum,
    .size = sizeof(fc_9_kernel_sum),
};

static cmsis_nn_fc_params fc_9_fc_params = {
    .input_offset = -fc_9_input_zero_point,
    .filter_offset = -fc_9_filter_zero_point,
    .output_offset = fc_9_output_zero_point,
    .activation.min = -128,
    .activation.max = 127,
};


const cmsis_nn_per_tensor_quant_params fc_9_quant_params = {
    .multiplier = fc_9_multiplier[0],
    .shift = fc_9_shift[0],
};


int32_t
str_ww_ref_model_fully_connected_9_init(void) {
    // Precompute kernel sums for each output channel.
    arm_vector_sum_s8(
        (int32_t *)fc_9_kernel_sum,
        fc_9_filter_dims.n,
        fc_9_filter_dims.c,
        fc_9_weights,
        fc_9_fc_params.input_offset,
        fc_9_fc_params.filter_offset,
        fc_9_bias
    );
    return 0;
}

int32_t
str_ww_ref_model_fully_connected_9_run(
    const int8_t* __restrict input,
    int8_t* __restrict output
) {


    return arm_fully_connected_s8(
        &fc_9_ctx,
        &fc_9_fc_params,
        &fc_9_quant_params,
        &fc_9_input_dims,
        input,
        &fc_9_filter_dims,
        fc_9_weights,
        &fc_9_bias_dims,
        fc_9_bias,
        &fc_9_output_dims,
        output
    );


}