/******************************************************************************
 * @file        str_ww_ref_model_resource_variables.c
 * @brief       Autogenerated AOT resource_variable kernel
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-08-05.
 *   This kernel represents node # in the corresponding graph.
 *
 * @date        2025-08-05
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/
#include <stdalign.h>
#include "str_ww_ref_model_resource_variables.h"

