/******************************************************************************
 * @file        str_ww_ref_model_model.c
 * @brief       Autogenerated AOT model
 * @details     This model was generated by HeliosAOT v0.2.2 on 2025-08-05.
 *   Subgraph: main.
 *   Model Description: MLIR Converted.
 * @version     v1.0.0
 * @date        2025-08-05
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdalign.h>
#include <stdint.h>
#include <math.h>
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "ns_ambiqsuite_harness.h"
#include "str_ww_ref_model_resource_variables.h"
#include "str_ww_ref_model_model.h"

#include "str_ww_ref_model_depthwise_conv_0.h"
#include "str_ww_ref_model_conv_1.h"
#include "str_ww_ref_model_depthwise_conv_2.h"
#include "str_ww_ref_model_conv_3.h"
#include "str_ww_ref_model_depthwise_conv_4.h"
#include "str_ww_ref_model_conv_5.h"
#include "str_ww_ref_model_depthwise_conv_6.h"
#include "str_ww_ref_model_conv_7.h"
#include "str_ww_ref_model_fully_connected_9.h"
#include "str_ww_ref_model_softmax_10.h"

// Verify CMSIS-NN version is compatible
#define EXPECTED_CMSIS_NN_VERSION_MAJOR  7
#define EXPECTED_CMSIS_NN_VERSION_MINOR  4
#define EXPECTED_CMSIS_NN_VERSION_PATCH  0

#if NS_CMSIS_NN_VERSION_MAJOR != EXPECTED_CMSIS_NN_VERSION_MAJOR
  #error "CMSIS-NN major version mismatch"
#elif NS_CMSIS_NN_VERSION_MINOR < EXPECTED_CMSIS_NN_VERSION_MINOR
  #error "CMSIS-NN minor version too old; need at least " STR(EXPECTED_CMSIS_NN_VERSION_MINOR)
#endif

const int32_t str_ww_ref_model_inputs_len[1] = {
    1200
};

const int32_t str_ww_ref_model_inputs_zero_point[1] = {
    -128
};

const float str_ww_ref_model_inputs_scale[1] = {
    0.0037010426
};

const int32_t str_ww_ref_model_outputs_len[1] = {
    3
};

const int32_t str_ww_ref_model_outputs_zero_point[1] = {
    -128
};

const float str_ww_ref_model_outputs_scale[1] = {
    0.00390625
};

alignas(16) static NS_PUT_IN_TCM int8_t model_buffer[7776];


int32_t str_ww_ref_model_model_init(str_ww_ref_model_model_context_t *context)
{

    int32_t status = 0;

    // Initializing operator 0 (depthwise_conv_0)
    if (context->callback) { context->callback(0, str_ww_ref_model_model_state_started, status, context->user_data); }
    status = str_ww_ref_model_depthwise_conv_0_init();
    if (context->callback) { context->callback(0, str_ww_ref_model_model_state_finished, status, context->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 1 (conv_1)
    if (context->callback) { context->callback(1, str_ww_ref_model_model_state_started, status, context->user_data); }
    status = str_ww_ref_model_conv_1_init();
    if (context->callback) { context->callback(1, str_ww_ref_model_model_state_finished, status, context->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 2 (depthwise_conv_2)
    if (context->callback) { context->callback(2, str_ww_ref_model_model_state_started, status, context->user_data); }
    status = str_ww_ref_model_depthwise_conv_2_init();
    if (context->callback) { context->callback(2, str_ww_ref_model_model_state_finished, status, context->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 3 (conv_3)
    if (context->callback) { context->callback(3, str_ww_ref_model_model_state_started, status, context->user_data); }
    status = str_ww_ref_model_conv_3_init();
    if (context->callback) { context->callback(3, str_ww_ref_model_model_state_finished, status, context->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 4 (depthwise_conv_4)
    if (context->callback) { context->callback(4, str_ww_ref_model_model_state_started, status, context->user_data); }
    status = str_ww_ref_model_depthwise_conv_4_init();
    if (context->callback) { context->callback(4, str_ww_ref_model_model_state_finished, status, context->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 5 (conv_5)
    if (context->callback) { context->callback(5, str_ww_ref_model_model_state_started, status, context->user_data); }
    status = str_ww_ref_model_conv_5_init();
    if (context->callback) { context->callback(5, str_ww_ref_model_model_state_finished, status, context->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 6 (depthwise_conv_6)
    if (context->callback) { context->callback(6, str_ww_ref_model_model_state_started, status, context->user_data); }
    status = str_ww_ref_model_depthwise_conv_6_init();
    if (context->callback) { context->callback(6, str_ww_ref_model_model_state_finished, status, context->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 7 (conv_7)
    if (context->callback) { context->callback(7, str_ww_ref_model_model_state_started, status, context->user_data); }
    status = str_ww_ref_model_conv_7_init();
    if (context->callback) { context->callback(7, str_ww_ref_model_model_state_finished, status, context->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 9 (fully_connected_9)
    if (context->callback) { context->callback(9, str_ww_ref_model_model_state_started, status, context->user_data); }
    status = str_ww_ref_model_fully_connected_9_init();
    if (context->callback) { context->callback(9, str_ww_ref_model_model_state_finished, status, context->user_data); }
    if (status != 0) { return status; }

    // Initializing operator 10 (softmax_10)
    if (context->callback) { context->callback(10, str_ww_ref_model_model_state_started, status, context->user_data); }
    status = str_ww_ref_model_softmax_10_init();
    if (context->callback) { context->callback(10, str_ww_ref_model_model_state_finished, status, context->user_data); }
    if (status != 0) { return status; }


    return status;
}

int32_t str_ww_ref_model_model_run(str_ww_ref_model_model_context_t *context)
{
    int8_t *buffer = model_buffer;
    int32_t status = 0;

    // Running operator 0 (depthwise_conv_0)
    if (context->callback) { context->callback(0, str_ww_ref_model_model_state_started, status, context->user_data); }

    status = str_ww_ref_model_depthwise_conv_0_run(
        context->input_data[0],
        (int8_t *)(buffer + 0)
    );

    if (context->callback) { context->callback(0, str_ww_ref_model_model_state_finished, status, context->user_data); }
    if (status != 0) { return status; }

    // Running operator 1 (conv_1)
    if (context->callback) { context->callback(1, str_ww_ref_model_model_state_started, status, context->user_data); }

    status = str_ww_ref_model_conv_1_run(
        (int8_t *)(buffer + 0),
        (int8_t *)(buffer + 1120)
    );

    if (context->callback) { context->callback(1, str_ww_ref_model_model_state_finished, status, context->user_data); }
    if (status != 0) { return status; }

    // Running operator 2 (depthwise_conv_2)
    if (context->callback) { context->callback(2, str_ww_ref_model_model_state_started, status, context->user_data); }

    status = str_ww_ref_model_depthwise_conv_2_run(
        (int8_t *)(buffer + 1120),
        (int8_t *)(buffer + 4704)
    );

    if (context->callback) { context->callback(2, str_ww_ref_model_model_state_finished, status, context->user_data); }
    if (status != 0) { return status; }

    // Running operator 3 (conv_3)
    if (context->callback) { context->callback(3, str_ww_ref_model_model_state_started, status, context->user_data); }

    status = str_ww_ref_model_conv_3_run(
        (int8_t *)(buffer + 4704),
        (int8_t *)(buffer + 0)
    );

    if (context->callback) { context->callback(3, str_ww_ref_model_model_state_finished, status, context->user_data); }
    if (status != 0) { return status; }

    // Running operator 4 (depthwise_conv_4)
    if (context->callback) { context->callback(4, str_ww_ref_model_model_state_started, status, context->user_data); }

    status = str_ww_ref_model_depthwise_conv_4_run(
        (int8_t *)(buffer + 0),
        (int8_t *)(buffer + 3072)
    );

    if (context->callback) { context->callback(4, str_ww_ref_model_model_state_finished, status, context->user_data); }
    if (status != 0) { return status; }

    // Running operator 5 (conv_5)
    if (context->callback) { context->callback(5, str_ww_ref_model_model_state_started, status, context->user_data); }

    status = str_ww_ref_model_conv_5_run(
        (int8_t *)(buffer + 3072),
        (int8_t *)(buffer + 0)
    );

    if (context->callback) { context->callback(5, str_ww_ref_model_model_state_finished, status, context->user_data); }
    if (status != 0) { return status; }

    // Running operator 6 (depthwise_conv_6)
    if (context->callback) { context->callback(6, str_ww_ref_model_model_state_started, status, context->user_data); }

    status = str_ww_ref_model_depthwise_conv_6_run(
        (int8_t *)(buffer + 0),
        (int8_t *)(buffer + 1920)
    );

    if (context->callback) { context->callback(6, str_ww_ref_model_model_state_finished, status, context->user_data); }
    if (status != 0) { return status; }

    // Running operator 7 (conv_7)
    if (context->callback) { context->callback(7, str_ww_ref_model_model_state_started, status, context->user_data); }

    status = str_ww_ref_model_conv_7_run(
        (int8_t *)(buffer + 1920),
        (int8_t *)(buffer + 0)
    );

    if (context->callback) { context->callback(7, str_ww_ref_model_model_state_finished, status, context->user_data); }
    if (status != 0) { return status; }

    // Running operator 9 (fully_connected_9)
    if (context->callback) { context->callback(9, str_ww_ref_model_model_state_started, status, context->user_data); }

    status = str_ww_ref_model_fully_connected_9_run(
        (int8_t *)(buffer + 0),
        (int8_t *)(buffer + 32)
    );

    if (context->callback) { context->callback(9, str_ww_ref_model_model_state_finished, status, context->user_data); }
    if (status != 0) { return status; }

    // Running operator 10 (softmax_10)
    if (context->callback) { context->callback(10, str_ww_ref_model_model_state_started, status, context->user_data); }

    status = str_ww_ref_model_softmax_10_run(
        (int8_t *)(buffer + 32),
        context->output_data[0]
    );

    if (context->callback) { context->callback(10, str_ww_ref_model_model_state_finished, status, context->user_data); }
    if (status != 0) { return status; }


    return status;
}