/******************************************************************************
 * @file        str_ww_ref_model_depthwise_conv_0.c
 * @brief       Autogenerated AOT DEPTHWISE_CONV_2D kernel
 * @details     This file was generated by HeliosAOT v0.2.2 on 2025-08-05.
 *   This kernel represents node #0 in the corresponding graph.
 *
 * @date        2025-08-05
 *
 * @copyright
 *   © 2025 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq’s sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE.txt” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/
#include <stdalign.h>
#include "ns_ambiqsuite_harness.h"
#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"
#include "str_ww_ref_model_depthwise_conv_0.h"

#if defined(ARM_MATH_MVEI)
#define SCRATCH_BUFFER_SIZE 1488
#define WEIGHT_SUM_BUFFER_SIZE 160
#elif defined(ARM_MATH_DSP)
#define SCRATCH_BUFFER_SIZE 0
#define WEIGHT_SUM_BUFFER_SIZE 0
#else
#define SCRATCH_BUFFER_SIZE 0
#define WEIGHT_SUM_BUFFER_SIZE 0
#endif

// Input dimensions: input shape is [1, H_IN, W_IN, C_IN]
static const cmsis_nn_dims dw_0_input_dims = { .n = 1, .h = 30, .w = 1, .c = 40 };

// Filter dimensions: weights shape is [1, H_FILT, W_FILT, C_OUT].
static const cmsis_nn_dims dw_0_filter_dims = { .n = 1, .h = 3, .w = 1, .c = 40 };

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims dw_0_bias_dims = { .n = 1, .h = 1, .w = 1, .c = 40 };

// Output dimensions: output shape is [1, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims dw_0_output_dims = { .n = 1, .h = 28, .w = 1, .c = 40 };

// Quantization parameters (per-channel quantization)
static const int32_t dw_0_multiplier[40] = {
    1268984915, 1998932673, 1195856596, 1135139039, 1806843644, 1154952868, 1774472765, 2047355720, 2126380885, 1362656616, 2027526343, 1168111440, 1760687700, 1165742101, 1568501852, 1866515162, 1901357852, 1733643241, 2085449832, 1967961301,
    1723109010, 1430772645, 1639425259, 1546261088, 1381383889, 1456210297, 1353194335, 1362968861, 1326872950, 1131328733, 2123972677, 1482776319, 1274549022, 1558493055, 1977069406, 1278658499, 1935322111, 1180946460, 1674669120, 1567800921
};
static const int32_t dw_0_shift[40] = {
    -8, -9, -7, -7, -8, -8, -8, -8, -8, -8, -8, -7, -8, -7, -8, -9, -8, -8, -8, -8,
    -8, -8, -8, -8, -8, -8, -8, -8, -8, -8, -8, -8, -8, -8, -9, -9, -8, -8, -9, -8
};

// Offsets and activation parameters.
static const int32_t dw_0_input_zero_point = -128;
static const int32_t dw_0_output_zero_point = -3;


// Weight and bias data.
alignas(16) static NS_PUT_IN_TCM int8_t dw_0_weights[] = {
    127, -103, 127, 20, -51, 47, 10, 127, 28, -85, -66, -1, -78, -127, 98, -116, 109, -54, 19, 20,
    -127, 68, -76, 100, 22, 2, -90, 34, -26, 127, -82, 127, 41, 127, -110, -79, 127, -59, -108, -14,
    91, -28, -42, -127, 127, 127, 127, 70, -127, -127, -127, 43, -127, 58, 127, -127, -42, -109, 127, 38,
    42, -50, -127, -96, -127, 127, 33, -28, -95, -22, 65, -54, 127, -55, 38, -28, -21, 7, -127, 50,
    -117, -127, -56, -7, 39, 5, -23, -120, -13, 34, 82, -127, 61, -22, -122, -82, -127, 127, 11, -127,
    96, -127, 99, -127, -1, -29, 127, -127, 127, 74, 127, -119, -39, -94, 127, -127, -108, 127, 117, 127
};

alignas(16) static NS_PUT_IN_TCM int32_t dw_0_bias[] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

alignas(16) static NS_PUT_IN_TCM int8_t dw_0_scratch_buffer[SCRATCH_BUFFER_SIZE];
alignas(16) static NS_PUT_IN_TCM int8_t dw_0_weight_sum_buffer[WEIGHT_SUM_BUFFER_SIZE];

static cmsis_nn_context dw_0_ctx = {
    .buf = dw_0_scratch_buffer,
    .size = sizeof(dw_0_scratch_buffer),
};

static cmsis_nn_context dw_0_weight_sum_ctx = {
    .buf = dw_0_weight_sum_buffer,
    .size = sizeof(dw_0_weight_sum_buffer),
};


const cmsis_nn_per_channel_quant_params dw_0_quant_params = {
    .multiplier = (int32_t*)dw_0_multiplier,
    .shift = (int32_t*)dw_0_shift,
};

const cmsis_nn_dw_conv_params dw_0_dw_conv_params = {
    .input_offset = -dw_0_input_zero_point,
    .output_offset = dw_0_output_zero_point,
    .ch_mult = 1,
    .stride.w = 1,
    .stride.h = 1,
    .padding.w = 0,
    .padding.h = 0,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t
str_ww_ref_model_depthwise_conv_0_init(void) {
    return arm_depthwise_convolve_weight_sum(
        (int32_t *)dw_0_weight_sum_buffer,
        NULL, // No scratch buffer required
        dw_0_weights,
        &dw_0_dw_conv_params,
        &dw_0_input_dims,
        &dw_0_filter_dims,
        &dw_0_output_dims,
        dw_0_dw_conv_params.input_offset,
        dw_0_bias
    );
}


int32_t
str_ww_ref_model_depthwise_conv_0_run(
    const int8_t* __restrict input,
    int8_t* __restrict output
) {

    return arm_depthwise_conv_wrapper_s8(
        &dw_0_ctx,
        &dw_0_weight_sum_ctx,
        &dw_0_dw_conv_params,
        &dw_0_quant_params,
        &dw_0_input_dims,
        input,
        &dw_0_filter_dims,
        dw_0_weights,
        &dw_0_bias_dims,
        dw_0_bias,
        &dw_0_output_dims,
        output
    );

}